# Base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Download NLTK data (stopwords and punkt)
RUN python -m nltk.downloader stopwords punkt

# Copy application files
COPY . /app

# Expose port
EXPOSE 8080

# Run the application
CMD ["python", "app.py"]
